# Generated by Django 4.1.5 on 2023-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('editora', models.CharField(max_length=75)),
                ('preco', models.FloatField()),
            ],
        ),
    ]
